#!/bin/bash
# exec container command
export ENVTYPE="staging"
if [ $ENVTYPE="staging" ]
then
  	exec npm run DATA_FILE="Questions-test.json"
else
  	exec npm run DATA_FILE="Questions-test.json"
fi
